package br.com.ccortez.deliveryofflinefirst

import android.app.Application
import android.content.Context
import androidx.test.runner.AndroidJUnitRunner

/**
 * Custom runner required for @HiltAndroidTest to work.
 *
 * Uses HiltTestApp_Application (generated by @CustomTestApplication(WorkerTestApplication::class))
 * instead of the bare HiltTestApplication. The generated class extends WorkerTestApplication,
 * which implements Configuration.Provider and provides HiltWorkerFactory to WorkManager —
 * preventing the NoSuchMethodException when @HiltWorker classes are instantiated in tests.
 */
@Suppress("unused") // referenced by name in build.gradle.kts testInstrumentationRunner
class HiltTestRunner : AndroidJUnitRunner() {
    override fun newApplication(
        cl: ClassLoader?,
        name: String?,
        context: Context?
    ): Application = super.newApplication(
        cl,
        "br.com.ccortez.deliveryofflinefirst.HiltTestApp_Application",
        context
    )
}
